server:
  port: 8000
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/geurime?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://localhost:3306/geurime?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ssafy506
    password: geurime506
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          # GOOGLE LOGIN
          google:
            client-id: 417526393965-udah7cpoj5lb6ko6svvrt9l0fglp9md6.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://geurime.com/api/login/oauth2/code/google
            scope: profile, email
          # KAKAO LOGIN
          kakao:
            client-id: c0cbf77489ed0d9b1b576570c815869f
            client-secret: EkRKIwjPLCyv1nMF0K9zhf2VtJWUBend
            redirect-uri: https://geurime.com/api/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email
        # KAKAO PROVIDER
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  # bucket4j ip주소 캐시
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
      config: classpath:ehcache.xml
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

decorator:
  datasource:
    p6spy:
      enable-logging: false

# bucket4j 설정
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      filter-method: servlet
      url: .*
      strategy: all
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your Request Quota\" }"
      rate-limits:
        - expression: "getRemoteAddr()"
          bandwidths:
            - capacity: 50
              time: 1
              unit: seconds
              fixed-refill-interval: 1
              fixed-refill-interval-unit: seconds

logging:
  level:
    root: info

# AWS S3
cloud:
  aws:
    credentials:
      access-key: AKIARUZDIPGQK3IJMXOW
      secret-key: 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
    s3:
      bucket: geurime-a506
    region:
      static: ap-northeast-2
    stack:
      auto: false
