server:
  port: 9000
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geurime?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ssafy506
    password: geurime506
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          # GOOGLE LOGIN
          google:
            client-id: 417526393965-udah7cpoj5lb6ko6svvrt9l0fglp9md6.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:9000/api/login/oauth2/code/google
            scope: profile, email
          # KAKAO LOGIN
          kakao:
            client-id: c0cbf77489ed0d9b1b576570c815869f
            client-secret: EkRKIwjPLCyv1nMF0K9zhf2VtJWUBend
            redirect-uri: http://localhost:9000/api/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email
        # KAKAO PROVIDER
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    root: info


